import { readFileSync, writeFileSync, existsSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, "..");
const envPath = join(rootDir, ".env");

// Minimal .env parser — no external dependency (e.g. dotenv) required.
function loadDotEnv(path) {
  if (!existsSync(path)) return {};
  const content = readFileSync(path, "utf-8");
  const result = {};
  content.split(/\r?\n/).forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) return;
    const eqIndex = trimmed.indexOf("=");
    if (eqIndex === -1) return;
    const key = trimmed.slice(0, eqIndex).trim();
    let value = trimmed.slice(eqIndex + 1).trim();
    value = value.replace(/^["']|["']$/g, ""); // strip surrounding quotes
    result[key] = value;
  });
  return result;
}

const fileEnv = loadDotEnv(envPath);
// Real environment variables (e.g. GitHub Actions secrets) take priority
// over a local .env file if both happen to be present.
const env = { ...fileEnv, ...process.env };

const required = [
  "FIREBASE_API_KEY",
  "FIREBASE_AUTH_DOMAIN",
  "FIREBASE_PROJECT_ID",
  "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_MESSAGING_SENDER_ID",
  "FIREBASE_APP_ID"
];

const missing = required.filter((key) => !env[key]);
if (missing.length) {
  console.error(`\n✖ Missing required environment variable(s): ${missing.join(", ")}`);
  console.error("  Create a .env file from .env.example (local dev), or set these");
  console.error("  as GitHub Actions repository secrets (deployment).\n");
  process.exit(1);
}

const output = `// ============================================================
// firebase-env.js — AUTO-GENERATED FILE. DO NOT EDIT OR COMMIT.
// Generated by scripts/generate-env.js from .env (local) or
// GitHub Actions secrets (CI/deploy). Regenerate any time by running:
//   node scripts/generate-env.js
// ============================================================

export const firebaseConfig = {
  apiKey: "${env.FIREBASE_API_KEY}",
  authDomain: "${env.FIREBASE_AUTH_DOMAIN}",
  projectId: "${env.FIREBASE_PROJECT_ID}",
  storageBucket: "${env.FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${env.FIREBASE_MESSAGING_SENDER_ID}",
  appId: "${env.FIREBASE_APP_ID}"
};
`;

writeFileSync(join(rootDir, "firebase-env.js"), output);
console.log("✔ firebase-env.js generated successfully.");
